### ISSUE TITLE
the mod m3u doesnt convert anything to a playable format for streamlink

### ISSUE THREAD

**Issue by merrychrishna** [ReenigneArcher/web2tv#24]
### Describe the Bug

i have converted an m3u but it does not play in streamlink

here is the command
C:\cygwin64\home\user\xteve2>python C:\cygwin64\home\user\xteve2\web2tv-main\m3u_modder.py -i http://localhost:8409/iptv/channels.m3u -o C:\cygwin64\home\user\xteve2\streamlink.m3u

 this is the output

#EXTM3U url-tvg="http://localhost:8409/iptv/xmltv.xml" x-tvg-url="http://localhost:8409/iptv/xmltv.xml"

#EXTINF:0 tvg-id="68.etv" channel-id="vP98rrCWT0O1gnFUt7IXRQ" channel-number="68" CUID="vP98rrCWT0O1gnFUt7IXRQ" tvg-chno="68" tvg-name="24/7 christmas favorites 3" tvg-logo="http://localhost:8409/iptv/logos/2CC550640213402C609F44B333CA521E.jpg" group-title="ErsatzTV" tvc-stream-vcodec="h264" tvc-stream-acodec="aac", 24/7 christmas favorites 3

httpstream://http://localhost:8409/iptv/channel/68.ts

### Operating System and Version

windows 10

### Python Version

Python 3.7.9

**Comment by merrychrishna** [comment]
i have to correct myself. i tested this link in command prompt

streamlink --loglevel info httpstream://http://localhost:8409/iptv/channel/71.ts --default-stream best


it plays successfully but my m3u does not play through xteve

**Comment by merrychrishna** [comment]
i think i need to create a corrosponding xmltv file but i dont know how to do that. ive been using the original xml file which isnt helping me play the stream

**Comment by merrychrishna** [comment]
how can i get this to work in xteve please?

**Comment by ReenigneArcher** [comment]
- Change the buffer to either ffmpeg or vlc
- Change the binary of the selected buffer to your streamlink binary: `C:\Program Files (x86)\Streamlink\bin\streamlink.exe`
- Change the buffer options: `--stdout --loglevel error [URL] --default-stream best`

![image](https://user-images.githubusercontent.com/42013603/154973415-a2de4a42-6d70-41ef-a52c-da0daa92ef8d.png)

**Comment by merrychrishna** [comment]
thats not my question. my settings already look like that. the plutotv.py script works perfectly like that. my issue is with the mod m3u py trying to convert an ersatz tv m3u to work in streamlink, not pluto tv. your mod m3u is not playable in streamlink wiith xteve that way. and the mod m3u does not create an xml file with the m3u

**Comment by merrychrishna** [comment]
![image](https://user-images.githubusercontent.com/59185469/154987925-af9016d7-4faf-4caa-9fbb-1ce46e187370.png)
this does not make a playable file

**Comment by merrychrishna** [comment]
why did you close this issue? you have not resolved it. nore did you wait for my response.

**Comment by ReenigneArcher** [comment]
> why did you close this issue? you have not resolved it. nore did you wait for my response.

There is no bug here to resolve. You are asking for support with software that I don't develop. You can try asking the devs of xteve or streamlink. You said the script does make it playable in streamlink, which is all it is supposed to.

> it plays successfully but my m3u does not play through xteve

I am not providing support for xteve

> my settings already look like that.

According to this comment TS streams do not work with streamlink (https://github.com/xteve-project/xTeVe/issues/198#issuecomment-749984462)... apparently they do as you said it works in command line, but apparently not in xteve.

P.S. If you're simply wanting to get this playlist working in streamlink so that you can run everything with one set of buffer options in xteve, you're going to have a lot of trouble. Most people run multiple instances of xteve with different buffer settings for each one. This is what their devs recommend.

**Comment by ReenigneArcher** [comment]
Also, I suggest you read up on github etiquette. You are dangerously close to being blocked. You have opened 7 issues/feature requests in the last 10 days. All of which are just questions, not bugs/issues, except 1 feature request, which was a duplicate.

https://developer.mozilla.org/en-US/docs/MDN/Contribute/Open_source_etiquette

![image](https://user-images.githubusercontent.com/42013603/154997312-6dfe50a8-8811-4ded-a21b-c157056e54ae.png)

**Comment by merrychrishna** [comment]
its not support for xteve. i found your script because you recommended xteve and streamlink as a workaround to someone elses plutoTV script in their issues tab. xteve support wont help with this because they dont support streamlink. youre the only one who would know what to do. i dont see why plutoTV.py works with xteve and streamlink but m3u_modder does not. i have multiple instances of xteve.

**Comment by merrychrishna** [comment]
sorry about the ettiquette and sounding demanding

the m3u does not work in streamlink either



```C:\cygwin64\home\user\xteve2>streamlink hls://file://C:/cygwin64/home/user/xteve2/streamlink.m3u --default-stream best
[cli][info] Found matching plugin hls for URL hls://file://C:/cygwin64/home/user/xteve2/streamlink.m3u
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (hls)
[cli][info] Starting player: "C:\Program Files\VideoLAN\VLC\vlc.exe" --file-caching=5000
[stream.hls][error] Failed to fetch segment 3: Unable to open URL: httpstream://http://localhost:8409/iptv/channel/71.ts (No connection adapters were found for 'httpstream://http//localhost:8409/iptv/channel/71.ts')
[stream.hls][error] Failed to fetch segment 4: Unable to open URL: httpstream://http://localhost:8409/iptv/channel/72.ts (No connection adapters were found for 'httpstream://http//localhost:8409/iptv/channel/72.ts')
[stream.hls][error] Failed to fetch segment 5: Unable to open URL: httpstream://http://localhost:8409/iptv/channel/73.ts (No connection adapters were found for 'httpstream://http//localhost:8409/iptv/channel/73.ts')
[cli][error] Try 1/1: Could not open stream <HLSStream('file://C:/cygwin64/home/user/xteve2/streamlink.m3u', None)> (Failed to read data from stream: Read timeout)
error: Could not open stream <HLSStream('file://C:/cygwin64/home/user/xteve2/streamlink.m3u', None)>, tried 1 times, exiting
[cli][info] Closing currently open stream...```

**Comment by merrychrishna** [comment]
oh i see what you mean. ts streams are not supported in streamlink

**Comment by ReenigneArcher** [comment]
I have never tried to open an m3u file directly in streamlink. I also don't use any ts streams in xteve. Again, I suggest discussing this at streamlink. They are the ones who helped me get it working in xteve to begin with.

https://github.com/streamlink/streamlink/discussions

Here's the link to the original discussion: https://github.com/streamlink/streamlink/discussions/3430

Anyway... m3u modder will not magically make your video playable in xteve. All it does is add the protocol which is required for streamlink. Otherwise they try to guess which protocol to use and sometimes are not successful in that. I don't really know what else to say.
